# Google Cloud builder script to deploy to GKE using skaffold
#   machineType: 'N1_HIGHCPU_8'
timeout: 1000s
steps:
- name: 'gcr.io/$PROJECT_ID/skaffold:alpha'
  dir: config
  args: ['run', '-f=skaffold-test.yaml' ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=eng-shared'
