# Skaffold for the full stack (eventually). Run:
# skaffold dev 
# If you quite skaffold, the directory PVC are not deleted. You need to manually delete:
# kubectl delete pvc --all
apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
  - image: gcr.io/engineering-devops/sk-ig
    context: ig
  - image: gcr.io/engineering-devops/sk-amster
    context: amster
  - image: gcr.io/engineering-devops/sk-am
    context: am
  - image: gcr.io/engineering-devops/sk-idm
    context: idm
  tagPolicy:
    sha256: {}
deploy:
  helm:
    # todo: this does not seem to work for setting a global -f 
    # flags:
    #   install:
    #   - "values: helm-common.yaml"
    releases:
    - name: frconfig
      chartPath: ../helm/frconfig
      valuesFiles:
      - helm-common.yaml
    - name: idrepo
      chartPath: ../helm/ds
      setValues:
        instance: idrepo
    - name: ig
      chartPath: ../helm/ig
      values:
        image: gcr.io/engineering-devops/sk-ig
      valuesFiles:
      - helm-common.yaml
    - name: sk-am
      chartPath: ../helm/am
      values:
        image: gcr.io/engineering-devops/sk-am
      valuesFiles:
      - helm-common.yaml
    - name: sk-amster
      chartPath: ../helm/amster
      values:
        image: gcr.io/engineering-devops/sk-amster
      valuesFiles:
      - helm-common.yaml
    - name: sk-amster
      chartPath: ../helm/idm
      values:
        image: gcr.io/engineering-devops/sk-idm
      valuesFiles:
      - helm-common.yaml
# todo: Create a GKE profile