# Skaffold for the full stack (eventually). Run:
# skaffold dev 
# If you quite skaffold, the directory PVC are not deleted. You need to manually delete:
# kubectl delete pvc --all
apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
  - image: gcr.io/engineering-devops/sk-ig
    context: ig
  - image: gcr.io/engineering-devops/sk-amster
    context: amster
  - image: gcr.io/engineering-devops/sk-am
    context: am
  - image: gcr.io/engineering-devops/sk-idm
    context: idm
  tagPolicy:
    sha256: {}
deploy:
  helm:
    flags:
      #install: [ '-f', 'helm-common.yaml']
      install: [ '-f', 'helm-test.yaml']
      upgrade: [ '-f', 'helm-test.yaml']
    releases:
    - name: frconfig
      chartPath: ../helm/frconfig
    - name: idrepo
      chartPath: ../helm/ds
      setValues:
        instance: idrepo
    - name: sk-am
      chartPath: ../helm/am
      values:
        image: gcr.io/engineering-devops/sk-am
    - name: sk-amster
      chartPath: ../helm/amster
      values:
        image: gcr.io/engineering-devops/sk-amster
    # - name: sk-idm
    #   chartPath: ../helm/idm
    #   values:
    #     image: gcr.io/engineering-devops/sk-idm
    # - name: ig
    #   chartPath: ../helm/ig
    #   values:
    #     image: gcr.io/engineering-devops/sk-ig
profiles:
# Profile used to initialize the idrepo ds instance with the skeleton AM config. AM file based config
# needs this to bootstrap. This limitation should be removed shortly.
- name: init
  deploy:
    helm:
      flags:
        # Change or update this values yaml for your environment
        install: ['-f', 'helm-test.yaml']
      releases:
      - name: idrepo
        chartPath: ../helm/ds
        setValues:
          instance: idrepo
      - name: sk-am
        chartPath: ../helm/am
        values:
          image: gcr.io/engineering-devops/sk-am
        setValues:
          catalinaOpts: "-server -Dcom.sun.identity.sm.sms_object_filebased_enabled=true"
      - name: sk-amster
        chartPath: ../helm/amster
        values:
          image: gcr.io/engineering-devops/sk-amster