apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
  - image: gcr.io/engineering-devops/sk-am
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
    - name: sk-am
      chartPath: ../../helm/am
      values:
        image: gcr.io/engineering-devops/sk-am
      setValues:
        devMode: true
      valuesFiles:
      - ../helm-common.yaml